package pho;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anh
 */
public class EmployeeLogin extends javax.swing.JFrame {
    DataBase data = new DataBase();

    /**
     * Creates new form EmployeeLogin
     */
    public EmployeeLogin() {
        initComponents();
        this.setLocationRelativeTo(null); // set frame to center of screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passWordText = new javax.swing.JPasswordField();
        userNameText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Login");
        setPreferredSize(new java.awt.Dimension(492, 310));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 100, 19);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 100, 19);

        passWordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passWordTextActionPerformed(evt);
            }
        });
        getContentPane().add(passWordText);
        passWordText.setBounds(120, 70, 120, 20);

        userNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextActionPerformed(evt);
            }
        });
        getContentPane().add(userNameText);
        userNameText.setBounds(120, 30, 120, 20);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 180, 80, 25);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 180, 80, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pho/Pho.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(480, 280));
        jLabel3.setMinimumSize(new java.awt.Dimension(480, 280));
        jLabel3.setPreferredSize(new java.awt.Dimension(480, 280));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 480, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user = userNameText.getText();
        String pass = passWordText.getText();
        CheckOut CO = new CheckOut();

        boolean checkLogin = false;
        for (int i=0; i<data.Username.length; i++){
            if (user.equals(data.Username[i]) && pass.equals(data.Password[i])){
                checkLogin = true;
                break;
            }
            
        }
        
        if (checkLogin){
            CO.setVisible(true);
            CO.jLabelName.setText(user);
            this.dispose();
        }
            
        else
            JOptionPane.showMessageDialog(null, "Your username or password is incorrect");
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButton1.doClick();
        }
    }//GEN-LAST:event_jButton1KeyPressed
    
    private void passWordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passWordTextActionPerformed
        // TODO add your handling code here:
        String user = userNameText.getText();
        String pass = passWordText.getText();
        CheckOut CO = new CheckOut();

        boolean checkLogin = false;
        for (int i=0; i<data.Username.length; i++){
            if (user.equals(data.Username[i]) && pass.equals(data.Password[i])){
                checkLogin = true;
                break;
            }
        }
        
        if (checkLogin){
            CO.setVisible(true);
            CO.jLabelName.setText(user);
            this.dispose();
        }
            
        else
            JOptionPane.showMessageDialog(null, "Your username or password is incorrect");       
    }//GEN-LAST:event_passWordTextActionPerformed

    private void userNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextActionPerformed
        // TODO add your handling code here:
        String user = userNameText.getText();
        String pass = passWordText.getText();
        CheckOut CO = new CheckOut();

        boolean checkLogin = false;
        for (int i=0; i<data.Username.length; i++){
            if (user.equals(data.Username[i]) && pass.equals(data.Password[i])){
                checkLogin = true;
                break;
            }
            
        }
        
        if (checkLogin){
            CO.setVisible(true);
            CO.jLabelName.setText(user);
            this.dispose();
        }
            
        else
            JOptionPane.showMessageDialog(null, "Your username or password is incorrect");
    }//GEN-LAST:event_userNameTextActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButton2.doClick();
        }
    }//GEN-LAST:event_jButton2KeyPressed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passWordText;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
}
